name: Update gamecache.sqlite.gz with BGG data

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:
jobs:
  index:
    # Skip entire job if neither new nor legacy token secret is configured
    if: ${{ secrets.GAMECACHE_GITHUB_TOKEN != '' || secrets.MYBGG_GITHUB_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps
        run: pip install -r scripts/requirements.txt
      - name: Run indexing
        env:
          GAMECACHE_GITHUB_TOKEN: ${{ secrets.GAMECACHE_GITHUB_TOKEN }}
          MYBGG_GITHUB_TOKEN: ${{ secrets.MYBGG_GITHUB_TOKEN }}
        run: python scripts/download_and_index.py --debug
